export const SOCKET_EVENT = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  JOIN_ROOM: "JOIN_ROOM",
  ADD_PEER: "ADD_PEER",
  REMOVE_PEER: "REMOVE_PEER",
  RELAY_SDP: "RELAY_SDP",
  RELAY_ICE: "RELAY_ICE",
  USER_SPEAKING: "USER_SPEAKING",
};
